class Provinces {
  final String name;

  const Provinces({required this.name});
}

const allProvinces = [
  Provinces(name: 'กรุงเทพมหานคร'),
  Provinces(name: 'กระบี่'),
  Provinces(name: 'กาญจนบุรี'),
  Provinces(name: 'กาฬสินธุ์'),
  Provinces(name: 'กำแพงเพชร'),
  Provinces(name: 'ขอนแก่น'),
  Provinces(name: 'จันทบุรี'),
  Provinces(name: 'ฉะเชิงเทรา'),
  Provinces(name: 'ชลบุรี'),
  Provinces(name: 'ชัยนาท'),
  Provinces(name: 'ชัยภูมิ'),
  Provinces(name: 'ชุมพร'),
  Provinces(name: 'เชียงราย'),
  Provinces(name: 'เชียงใหม่'),
  Provinces(name: 'ตรัง'),
  Provinces(name: 'ตราด'),
  Provinces(name: 'ตาก'),
  Provinces(name: 'นครนายก'),
  Provinces(name: 'นครปฐม'),
  Provinces(name: 'นครพนม'),
  Provinces(name: 'นครราชสีมา'),
  Provinces(name: 'นครศรีธรรมราช'),
  Provinces(name: 'นครสวรรค์'),
  Provinces(name: 'นนทบุรี'),
  Provinces(name: 'นราธิวาส'),
  Provinces(name: 'น่าน'),
  Provinces(name: 'บึงกาฬ'),
  Provinces(name: 'บุรีรัมย์'),
  Provinces(name: 'ปทุมธานี'),
  Provinces(name: 'ประจวบคีรีขันธ์'),
  Provinces(name: 'ปราจีนบุรี'),
  Provinces(name: 'ปัตตานี'),
  Provinces(name: 'พระนครศรีอยุธยา'),
  Provinces(name: 'พังงา'),
  Provinces(name: 'พัทลุง'),
  Provinces(name: 'พิจิตร'),
  Provinces(name: 'พิษณุโลก'),
  Provinces(name: 'เพชรบุรี'),
  Provinces(name: 'เพชรบูรณ์'),
  Provinces(name: 'แพร่'),
  Provinces(name: 'พะเยา'),
  Provinces(name: 'ภูเก็ต'),
  Provinces(name: 'มหาสารคาม'),
  Provinces(name: 'มุกดาหาร'),
  Provinces(name: 'แม่ฮ่องสอน'),
  Provinces(name: 'ยโสธร'),
  Provinces(name: 'ยะลา'),
  Provinces(name: 'ร้อยเอ็ด'),
  Provinces(name: 'ระนอง'),
  Provinces(name: 'ระยอง'),
  Provinces(name: 'ราชบุรี'),
  Provinces(name: 'ลพบุรี'),
  Provinces(name: 'ลำปาง'),
  Provinces(name: 'ลำพูน'),
  Provinces(name: 'เลย'),
  Provinces(name: 'ศรีสะเกษ'),
  Provinces(name: 'สกลนคร'),
  Provinces(name: 'สงขลา'),
  Provinces(name: 'สตูล'),
  Provinces(name: 'สมุทรปราการ'),
  Provinces(name: 'สมุทรสงคราม'),
  Provinces(name: 'สมุทรสาคร'),
  Provinces(name: 'สระแก้ว'),
  Provinces(name: 'สระบุรี'),
  Provinces(name: 'สิงห์บุรี'),
  Provinces(name: 'สุโขทัย'),
  Provinces(name: 'สุพรรณบุรี'),
  Provinces(name: 'สุราษฎร์ธานี'),
  Provinces(name: 'สุรินทร์'),
  Provinces(name: 'หนองคาย'),
  Provinces(name: 'หนองบัวลำภู'),
  Provinces(name: 'อ่างทอง'),
  Provinces(name: 'อุดรธานี'),
  Provinces(name: 'อุทัยธานี'),
  Provinces(name: 'อุตรดิตถ์'),
  Provinces(name: 'อุบลราชธานี'),
  Provinces(name: 'อำนาจเจริญ'),
];

void main() {
  print(allProvinces.length);
}
